# Generated by Django 4.1.2 on 2022-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoresCine', '0002_peliculas_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
