# Generated by Django 4.1.2 on 2022-11-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoresCine', '0003_peliculas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='id_pelicula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
