# Generated by Django 4.1.2 on 2022-11-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directoresCine', '0005_remove_directores_id_pelicula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directores',
            old_name='Fecha_nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
